use std::{ffi::OsStr, fmt::Display};

pub enum Language {
    Rust,
    Python,
    JavaScript,
    TypeScript,
    JSX,
    TSX,
    Java,
    CSharp,
    CPlusPlus,
    C,
    Go,
    Ruby,
    PHP,
    Swift,
    Kotlin,
    Scala,
    R,
    Dart,
    Lua,
    Perl,
    Shell,
    PowerShell,
    Haskell,
    Elixir,
    Erlang,
    Clojure,
    FSharp,
    OCaml,
    Zig,
    Nim,
    Crystal,
    Julia,
    ObjectiveC,
    HTML,
    CSS,
    SCSS,
    SASS,
    Less,
    JSON,
    XML,
    YAML,
    TOML,
    Markdown,
    SQL,
    GraphQL,
    Dockerfile,
    Makefile,
    CMake,
    Protobuf,
    Thrift,
    LinkerScript,
}

impl Language {
    pub fn from_ext(ext: &OsStr) -> Option<Self> {
        let ext = ext.to_str()?;

        let res = match ext {
            "rs" | "rs.in" => Self::Rust,
            "py" | "pyw" | "pyi" => Self::Python,
            "js" | "mjs" | "cjs" => Self::JavaScript,
            "ts" | "mts" | "cts" => Self::TypeScript,
            "jsx" => Self::JSX,
            "tsx" => Self::TSX,
            "java" => Self::Java,
            "cs" | "csx" => Self::CSharp,
            "cpp" | "cc" | "cxx" | "c++" | "hpp" | "hh" | "hxx" | "h++" => Self::CPlusPlus,
            "c" | "h" => Self::C,
            "go" => Self::Go,
            "rb" | "rake" | "gemspec" => Self::Ruby,
            "php" | "phtml" | "php3" | "php4" | "php5" | "phps" => Self::PHP,
            "swift" => Self::Swift,
            "kt" | "kts" | "ktm" => Self::Kotlin,
            "scala" | "sc" => Self::Scala,
            "r" | "R" | "rdata" | "rds" | "rda" => Self::R,
            "dart" => Self::Dart,
            "lua" => Self::Lua,
            "pl" | "pm" | "t" | "pod" => Self::Perl,
            "sh" | "bash" | "zsh" | "fish" => Self::Shell,
            "ps1" | "psm1" | "psd1" => Self::PowerShell,
            "hs" | "lhs" => Self::Haskell,
            "ex" | "exs" => Self::Elixir,
            "erl" | "hrl" => Self::Erlang,
            "clj" | "cljs" | "cljc" | "edn" => Self::Clojure,
            "fs" | "fsi" | "fsx" | "fsscript" => Self::FSharp,
            "ml" | "mli" => Self::OCaml,
            "zig" => Self::Zig,
            "nim" | "nims" | "nimble" => Self::Nim,
            "cr" => Self::Crystal,
            "jl" => Self::Julia,
            "m" | "mm" => Self::ObjectiveC,
            "html" | "htm" | "xhtml" => Self::HTML,
            "css" => Self::CSS,
            "scss" => Self::SCSS,
            "sass" => Self::SASS,
            "less" => Self::Less,
            "json" | "jsonc" | "json5" => Self::JSON,
            "xml" | "xsl" | "xsd" | "svg" => Self::XML,
            "yml" | "yaml" => Self::YAML,
            "toml" => Self::TOML,
            "md" | "markdown" | "mdown" | "mkd" | "mkdn" => Self::Markdown,
            "sql" | "mysql" | "pgsql" | "plsql" => Self::SQL,
            "graphql" | "gql" => Self::GraphQL,
            "dockerfile" => Self::Dockerfile,
            "makefile" | "mk" | "mak" => Self::Makefile,
            "cmake" => Self::CMake,
            "proto" => Self::Protobuf,
            "thrift" => Self::Thrift,
            "ld" | "lds" | "x" => Self::LinkerScript,
            _ => return None,
        };

        Some(res)
    }
}

impl Display for Language {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rust => write!(f, "Rust"),
            Self::Python => write!(f, "Python"),
            Self::JavaScript => write!(f, "JavaScript"),
            Self::TypeScript => write!(f, "TypeScript"),
            Self::JSX => write!(f, "JSX"),
            Self::TSX => write!(f, "TSX"),
            Self::Java => write!(f, "Java"),
            Self::CSharp => write!(f, "C#"),
            Self::CPlusPlus => write!(f, "C++"),
            Self::C => write!(f, "C"),
            Self::Go => write!(f, "Go"),
            Self::Ruby => write!(f, "Ruby"),
            Self::PHP => write!(f, "PHP"),
            Self::Swift => write!(f, "Swift"),
            Self::Kotlin => write!(f, "Kotlin"),
            Self::Scala => write!(f, "Scala"),
            Self::R => write!(f, "R"),
            Self::Dart => write!(f, "Dart"),
            Self::Lua => write!(f, "Lua"),
            Self::Perl => write!(f, "Perl"),
            Self::Shell => write!(f, "Shell"),
            Self::PowerShell => write!(f, "PowerShell"),
            Self::Haskell => write!(f, "Haskell"),
            Self::Elixir => write!(f, "Elixir"),
            Self::Erlang => write!(f, "Erlang"),
            Self::Clojure => write!(f, "Clojure"),
            Self::FSharp => write!(f, "F#"),
            Self::OCaml => write!(f, "OCaml"),
            Self::Zig => write!(f, "Zig"),
            Self::Nim => write!(f, "Nim"),
            Self::Crystal => write!(f, "Crystal"),
            Self::Julia => write!(f, "Julia"),
            Self::ObjectiveC => write!(f, "Objective-C"),
            Self::HTML => write!(f, "HTML"),
            Self::CSS => write!(f, "CSS"),
            Self::SCSS => write!(f, "SCSS"),
            Self::SASS => write!(f, "SASS"),
            Self::Less => write!(f, "Less"),
            Self::JSON => write!(f, "JSON"),
            Self::XML => write!(f, "XML"),
            Self::YAML => write!(f, "YAML"),
            Self::TOML => write!(f, "TOML"),
            Self::Markdown => write!(f, "Markdown"),
            Self::SQL => write!(f, "SQL"),
            Self::GraphQL => write!(f, "GraphQL"),
            Self::Dockerfile => write!(f, "Dockerfile"),
            Self::Makefile => write!(f, "Makefile"),
            Self::CMake => write!(f, "CMake"),
            Self::Protobuf => write!(f, "Protocol Buffers"),
            Self::Thrift => write!(f, "Thrift"),
            Self::LinkerScript => write!(f, "Linker Script"),
        }
    }
}
